const ReadlineSync =require('readline-Sync');
const Hourly_wage =ReadlineSync.question('\nHourly wage: ');
const Monday =ReadlineSync.question('\nMonday: ');
const Tuesday =ReadlineSync.question('Tuesday: ');
const Wednesday =ReadlineSync.question('Wednesday: ');
const Thursday =ReadlineSync.question('Thursday: ');
const Friday =ReadlineSync.question('Friday: ');
const Saturday =ReadlineSync.question('Saturday: ');
const Sunday =ReadlineSync.question('Sunday: ');
const Total_hours =(Monday + Tuesday + Wednesday + Thursday + Friday + Saturday + Sunday);
let Wage =('12.5');
let Total =('53' * '12.5').toLocaleString('en', { minimunFractionDigits: 2, maximumFractionDigits: 2});
console.log("\nYou'll make $" + Total + " this week.");
